using DataObject;
using ProcessModel;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Script.Services;
using System.Web.Services;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace HRMS.View.Modules
{
    public partial class EmployeeRegistration : Page
    {
        protected string UserId = null;
        private readonly EmployeeOnboardingBL onboardingBL = new EmployeeOnboardingBL();
        private const string DefaultEmployeePassword = "Pass@123";

        protected void Page_Load(object sender, EventArgs e)
        {
            UserId = Convert.ToString(Session["userId"]);
            if (string.Equals(Request.QueryString["action"], "checkDuplicate", StringComparison.OrdinalIgnoreCase))
            {
                WriteDuplicateValidationResponse();
                return;
            }

            if (!IsPostBack)
            {
                BindLookupDropdowns();
            }

            // The Repeater's item controls (including the FileUpload rows) must be
            // recreated on every request, not just the initial load, otherwise the
            // control tree won't exist for the submit postback to resolve against.
            BindDocumentUploadRows();
        }

        private void WriteDuplicateValidationResponse()
        {
            string fieldName = Convert.ToString(Request.QueryString["fieldName"] ?? string.Empty);
            string fieldValue = Convert.ToString(Request.QueryString["fieldValue"] ?? string.Empty);
            string message = onboardingBL.CheckEmployeeOnboardingDuplicate(fieldName, fieldValue, 0);
            bool isDuplicate = !string.IsNullOrWhiteSpace(message);

            Response.Clear();
            Response.ContentType = "application/json";
            Response.Write("{\"IsDuplicate\":" + (isDuplicate ? "true" : "false") + ",\"Message\":\"" + HttpUtility.JavaScriptStringEncode(message) + "\"}");
            Response.End();
        }

        private void BindLookupDropdowns()
        {
            BindLookup(ddlGender, "Gender");
            BindLookup(ddlMaritalStatus, "Marital Status");
            BindLookup(ddlBloodGroup, "Blood Group");
            BindLookup(ddlNationality, "Nationality");
            BindLookup(ddlEmploymentType, "Emptype");
            BindLookup(ddlEmployeeCategory, "Emp Category");
            BindLookupValue(ddlProbationPeriod, "probation_month");
            BindLookup(ddlEmployeeStatus, "EmpStatus");
            BindLookup(ddlEmployeeSubStatus, "EmpSubStatus");  //sagar 10-07-2026
            BindLookup(ddlSeparationReason, "Separation Reason");
            //BindProcedureDropdown(ddlCompany, "Sp_BindDropdownCompany");
            BindLookup(ddlDepartment, "Department");
            BindProcedureDropdown(ddlDesignation, "sp_bindDesignations");
            BindProcedureDropdown(ddlReportingManager, "sp_bindassignby");
            //BindProcedureDropdown(ddlFunctionalManager, "get_hod_fun_manager", "Functional Manager");
            BindProcedureDropdown(ddlHod, "get_hod_fun_manager", "HOD");
            //BindLookup(ddlEmployeeLevel, "Employee Level");
            BindLookup(ddlAttendanceType, "Attendance Type");
            BindLookup(ddlWeeklyOff, "Weekly Off");
            BindLookup(ddlAttendancePolicy, "Attendance Policy");
            BindLookup(ddlWorkLocation, "Work Location");
            BindTextBox(txtEmployeeCode, "txtEmployeeCode"); //Sagar 10-07-2026
        }

        private void BindDocumentUploadRows()
        {
            rptDocumentUpload.DataSource = new CommonBL().dropdownDocuments();
            rptDocumentUpload.DataBind();
        }


        private void BindTextBox(HtmlInputText txt,string textBoxType)
        {
            EmployeeOnboardingResponseDO response = onboardingBL.GetTextBoxValue(textBoxType);
            txt.Value = response.AutogeneratedEmpCode.ToString();
        }
        private void BindLookup(DropDownList ddl, string lookupType)
        {
            ddl.DataSource = onboardingBL.BindLookupData(lookupType);
            ddl.DataTextField = "Text";
            ddl.DataValueField = "Id";
            ddl.DataBind();
            AddDisabledSelectOption(ddl);
        }

        private void BindLookupValue(DropDownList ddl, string lookupType)
        {
            ddl.DataSource = onboardingBL.BindLookupData(lookupType);
            ddl.DataTextField = "Text";
            ddl.DataValueField = "Value";
            ddl.DataBind();
            AddDisabledSelectOption(ddl);
        }

        private void BindProcedureDropdown(DropDownList ddl, string storedProcedureName, string lookupType = null)
        {
            ddl.DataSource = onboardingBL.BindStoredProcedureDropdown(storedProcedureName, lookupType);
            ddl.DataTextField = "Text";
            ddl.DataValueField = "Id";
            ddl.DataBind();
            AddDisabledSelectOption(ddl);
        }

        private void AddDisabledSelectOption(DropDownList ddl)
        {
            ListItem selectItem = new ListItem("-- Select --", string.Empty);
            selectItem.Attributes["disabled"] = "disabled";
            selectItem.Attributes["hidden"] = "hidden";
            ddl.Items.Insert(0, selectItem);
            ddl.ClearSelection();
            ddl.Items[0].Selected = true;
        }

        protected void SubmitEmployee_Click(object sender, EventArgs e)
        {
            try
            {
                MandatoryFieldError validationError = ValidateMandatoryFields();
                if (validationError != null)
                {
                    string encodedMessage = HttpUtility.JavaScriptStringEncode(validationError.Message);
                    string script =
                        "if(window.Swal){Swal.fire({icon:'warning',title:'Please fill mandatory fields',text:'" + encodedMessage + "',confirmButtonColor:'#2563EB'});}else{alert('" + encodedMessage + "');}"
                        + "if(window.applyServerFieldValidationError){applyServerFieldValidationError('" + HttpUtility.JavaScriptStringEncode(validationError.ElementId) + "','" + HttpUtility.JavaScriptStringEncode(validationError.MessageId) + "','" + encodedMessage + "');}";

                    ClientScript.RegisterStartupScript(
                        GetType(),
                        "EmployeeOnboardingValidation",
                        script,
                        true);
                    return;
                }

                EmployeeOnboardingDO employee = BuildEmployeeOnboarding();
                EmployeeOnboardingResponseDO response = onboardingBL.SaveEmployeeOnboarding(employee);

                if (string.Equals(response.Status, "Success", StringComparison.OrdinalIgnoreCase))
                {
                    SaveEmployeeDocuments(response.UserId, employee.Email, employee.EmployeeCode);

                    string generatedPassword = DefaultEmployeePassword;

                    if (chkSendCredentials.Checked && !string.IsNullOrWhiteSpace(employee.Email))
                    {
                        try
                        {
                            UserDetailsBL userDetailsBL = new UserDetailsBL();
                            userDetailsBL.SendUserCredentialsMail(employee.Email, employee.Username, generatedPassword);
                        }
                        catch (Exception mailEx)
                        {
                            CommonBL errorlog = new CommonBL();
                            errorlog.fnStoreErrorLog("EmployeeRegistration", "SubmitEmployee_Click_SendMail", "Exception Message: " + mailEx.Message + " StackTrace: " + mailEx.StackTrace, UserId);
                        }
                    }

                    litEmployeeId.Text = response.UserId.ToString();
                    litUsername.Text = HttpUtility.HtmlEncode(employee.Username);
                    litPassword.Text = HttpUtility.HtmlEncode(generatedPassword);

                    string script = @"
                        if (document.getElementById('statusText')) {
                            document.getElementById('statusText').textContent = 'Employee created';
                        }

                        if (window.Swal) {
                            Swal.fire({
                                icon: 'success',
                                title: 'Employee Registered Successfully',
                                confirmButtonText: 'Go To Employee List',
                                showDenyButton: true,
                                denyButtonText: 'Create Another',
                                confirmButtonColor: '#2563EB',
                                denyButtonColor: '#64748B',
                                allowOutsideClick: true,
                                timer: 1500,
                                timerProgressBar: true
                            }).then(function (result) {
                                if (result.isConfirmed) {
                                    window.location.href = '/View/Modules/EmployeeList.aspx';
                                } else {
                                    window.location.href = '/View/Modules/EmployeeRegistration.aspx';
                                }
                            });
                        } else {
                            alert('Employee Registered Successfully');
                            window.location.href = '/View/Modules/EmployeeRegistration.aspx';
                        }";
                    ClientScript.RegisterStartupScript(GetType(), "EmployeeOnboardingSaved", script, true);
                    return;
                }

                string message = HttpUtility.JavaScriptStringEncode(string.IsNullOrWhiteSpace(response.Message)
                    ? "Employee onboarding save failed."
                    : response.Message);

                ClientScript.RegisterStartupScript(
                    GetType(),
                    "EmployeeOnboardingFailed",
                    "if(window.Swal){Swal.fire({icon:'error',title:'Employee onboarding save failed',text:'" + message + "',confirmButtonColor:'#2563EB'});}else{alert('" + message + "');}",
                    true);
            }
            catch (Exception ex)
            {
                CommonBL errorlog = new CommonBL();
                errorlog.fnStoreErrorLog("EmployeeRegistration", "SubmitEmployee_Click", "Exception Message: " + ex.Message + " StackTrace: " + ex.StackTrace, UserId);

                ClientScript.RegisterStartupScript(
                    GetType(),
                    "EmployeeOnboardingException",
                    "if(window.Swal){Swal.fire({icon:'error',title:'Employee onboarding save failed',text:'Please try again or contact support.',confirmButtonColor:'#2563EB'});}else{alert('Employee onboarding save failed. Please try again or contact support.');}",
                    true);
            }
        }

        [WebMethod]
        [ScriptMethod(ResponseFormat = ResponseFormat.Json)]
        public static EmployeeDuplicateValidationResponse CheckEmployeeDuplicate(string fieldName, string fieldValue)
        {
            EmployeeDuplicateValidationResponse response = new EmployeeDuplicateValidationResponse
            {
                IsDuplicate = false,
                Message = string.Empty
            };

            try
            {
                EmployeeOnboardingBL onboardingBL = new EmployeeOnboardingBL();
                string message = onboardingBL.CheckEmployeeOnboardingDuplicate(fieldName, fieldValue, 0);
                response.IsDuplicate = !string.IsNullOrWhiteSpace(message);
                response.Message = message;
            }
            catch
            {
                response.IsDuplicate = false;
                response.Message = string.Empty;
            }

            return response;
        }

        public class EmployeeDuplicateValidationResponse
        {
            public bool IsDuplicate { get; set; }
            public string Message { get; set; }
        }

        private class MandatoryFieldError
        {
            public string ElementId { get; set; }
            public string MessageId { get; set; }
            public string Message { get; set; }
        }

        private MandatoryFieldError FieldError(string elementId, string messageId, string message)
        {
            return new MandatoryFieldError { ElementId = elementId, MessageId = messageId, Message = message };
        }

        private MandatoryFieldError ValidateMandatoryFields()
        {
            if (string.IsNullOrWhiteSpace(ValueOf(txtEmployeeCode))) return FieldError(txtEmployeeCode.ClientID, "employeeCodeDuplicateMessage", "Employee Code is required.");
            if (string.IsNullOrWhiteSpace(ValueOf(txtUsername))) return FieldError(txtUsername.ClientID, "usernameDuplicateMessage", "Username is required.");
            if (string.IsNullOrWhiteSpace(ValueOf(txtFirstName))) return FieldError(txtFirstName.ClientID, "firstNameValidationMessage", "First Name is required.");
            if (!Regex.IsMatch(ValueOf(txtFirstName), @"^[A-Za-z ]+$")) return FieldError(txtFirstName.ClientID, "firstNameValidationMessage", "Write name in correct format.");
            if (!string.IsNullOrWhiteSpace(ValueOf(txtMiddleName)) && !Regex.IsMatch(ValueOf(txtMiddleName), @"^[A-Za-z ]+$")) return FieldError(txtMiddleName.ClientID, "middleNameValidationMessage", "Write name in correct format.");
            if (string.IsNullOrWhiteSpace(ValueOf(txtLastName))) return FieldError(txtLastName.ClientID, "lastNameValidationMessage", "Last Name is required.");
            if (!Regex.IsMatch(ValueOf(txtLastName), @"^[A-Za-z ]+$")) return FieldError(txtLastName.ClientID, "lastNameValidationMessage", "Write name in correct format.");
            if (string.IsNullOrWhiteSpace(ValueOf(txtEmail))) return FieldError(txtEmail.ClientID, "emailDuplicateMessage", "Email ID is required.");
            if (!Regex.IsMatch(ValueOf(txtEmail), @"^[^\s@]+@[^\s@]+\.[^\s@]{2,}$")) return FieldError(txtEmail.ClientID, "emailDuplicateMessage", "Enter a valid Email ID.");
            if (string.IsNullOrWhiteSpace(ValueOf(txtMobileNumber))) return FieldError(txtMobileNumber.ClientID, "mobileDuplicateMessage", "Mobile Number is required.");
            if (!Regex.IsMatch(ValueOf(txtMobileNumber), @"^\d{10}$")) return FieldError(txtMobileNumber.ClientID, "mobileDuplicateMessage", "Mobile Number must be 10 digits.");
            if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlGender))) return FieldError(ddlGender.ClientID, "genderRequiredMessage", "Gender is required.");
            if (string.IsNullOrWhiteSpace(ValueOf(txtDateOfBirth))) return FieldError(txtDateOfBirth.ClientID, "dobRequiredMessage", "Date of Birth is required.");
            if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlNationality))) return FieldError(ddlNationality.ClientID, "nationalityRequiredMessage", "Nationality is required.");
            if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlMaritalStatus))) return FieldError(ddlMaritalStatus.ClientID, "maritalStatusRequiredMessage", "Marital Status is required.");
            if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlBloodGroup))) return FieldError(ddlBloodGroup.ClientID, "bloodGroupRequiredMessage", "Blood Group is required.");
            if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlEmploymentType))) return FieldError(ddlEmploymentType.ClientID, "employmentTypeRequiredMessage", "Employment Type is required.");
            if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlEmployeeCategory))) return FieldError(ddlEmployeeCategory.ClientID, "employeeCategoryRequiredMessage", "Employee Category is required.");
            if (string.IsNullOrWhiteSpace(ValueOf(txtJoiningDate))) return FieldError(txtJoiningDate.ClientID, "joiningDateRequiredMessage", "Joining Date is required.");
            if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlProbationPeriod))) return FieldError(ddlProbationPeriod.ClientID, "probationPeriodRequiredMessage", "Probation Period is required.");
            if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlEmployeeStatus))) return FieldError(ddlEmployeeStatus.ClientID, "employeeStatusRequiredMessage", "Employee Status is required.");
            if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlEmployeeSubStatus))) return FieldError(ddlEmployeeSubStatus.ClientID, "employeeSubStatusRequiredMessage", "Employee Sub Status is required.");
            //if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlCompany))) return FieldError(ddlCompany.ClientID, "companyRequiredMessage", "Company is required.");
            if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlDepartment))) return FieldError(ddlDepartment.ClientID, "departmentRequiredMessage", "Department is required.");
            if (string.IsNullOrWhiteSpace(ValueOf(txtBranchOffice))) return FieldError(txtBranchOffice.ClientID, "branchOfficeRequiredMessage", "Branch Office is required.");
            if (string.IsNullOrWhiteSpace(ValueOf(txtLocation))) return FieldError(txtLocation.ClientID, "locationRequiredMessage", "Location is required.");
            if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlDesignation))) return FieldError(ddlDesignation.ClientID, "designationRequiredMessage", "Designation is required.");
            if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlReportingManager))) return FieldError(ddlReportingManager.ClientID, "reportingManagerRequiredMessage", "Reporting Manager is required.");

            //if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlFunctionalManager))) return FieldError(ddlFunctionalManager.ClientID, "functionalManagerRequiredMessage", "Functional Manager is required.");
            if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlHod))) return FieldError(ddlHod.ClientID, "hodRequiredMessage", "HOD is required.");
            if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlAttendanceType))) return FieldError(ddlAttendanceType.ClientID, "attendanceTypeRequiredMessage", "Attendance Type is required.");
            if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlWeeklyOff))) return FieldError(ddlWeeklyOff.ClientID, "weeklyOffRequiredMessage", "Weekly Off is required.");
            if (string.IsNullOrWhiteSpace(ValueOf(txtWorkingHours))) return FieldError(txtWorkingHours.ClientID, "workingHoursValidationMessage", "Working Hours is required.");
            if (!Regex.IsMatch(ValueOf(txtWorkingHours), @"^([0-9]|[01][0-9]|2[0-3]):[0-5][0-9]$")) return FieldError(txtWorkingHours.ClientID, "workingHoursValidationMessage", "Working Hours must be in HH:mm format.");
            if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlAttendancePolicy))) return FieldError(ddlAttendancePolicy.ClientID, "attendancePolicyRequiredMessage", "Attendance Policy is required.");
            if (string.IsNullOrWhiteSpace(ValueOf(txtPunchingDeviceId))) return FieldError(txtPunchingDeviceId.ClientID, "punchingDeviceIdRequiredMessage", "Punching Device ID is required.");
            if (string.IsNullOrWhiteSpace(ValueOf(txtBiometricId))) return FieldError(txtBiometricId.ClientID, "biometricIdRequiredMessage", "Biometric ID is required.");
            if (chkOvertimeEligible.Checked && string.IsNullOrWhiteSpace(ValueOf(txtOvertimeRate))) return FieldError(txtOvertimeRate.ClientID, "overtimeRateRequiredMessage", "Overtime Rate is required.");
            if (string.IsNullOrWhiteSpace(SelectedValueOf(ddlWorkLocation))) return FieldError(ddlWorkLocation.ClientID, "workLocationRequiredMessage", "Work Location is required.");

            return null;
        }

        private static readonly string[] AllowedDocumentExtensions = { ".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp", ".pdf" };

        private void SaveEmployeeDocuments(int userId, string employeeEmail, string employeeCode)
        {
            const int maxFileSize = 3 * 1024 * 1024;
            string documentsRoot = ConfigurationManager.AppSettings["EmployeeDocumentServerPath"];
            if (documentsRoot.StartsWith("~"))
            {
                documentsRoot = Server.MapPath(documentsRoot);
            }

            DateTime now = DateTime.Now;
            string basePath = Path.Combine(
                documentsRoot,
                now.Year.ToString(),
                now.Month.ToString("00"),
                employeeCode ?? string.Empty) + Path.DirectorySeparatorChar;

            userDocumentBL userDocBL = new userDocumentBL();

            foreach (RepeaterItem item in rptDocumentUpload.Items)
            {
                FileUpload fileUpload = item.FindControl("fuDocument") as FileUpload;
                HiddenField documentTypeIdField = item.FindControl("hdnDocumentTypeId") as HiddenField;
                int documentMasterId = documentTypeIdField != null ? ParseInt(documentTypeIdField.Value) : 0;

                if (fileUpload == null || !fileUpload.HasFile || documentMasterId <= 0)
                {
                    continue;
                }

                try
                {
                    if (fileUpload.PostedFile.ContentLength > maxFileSize)
                    {
                        continue;
                    }

                    string originalFileName = Path.GetFileName(fileUpload.FileName);
                    string fileNameWithoutExt = Path.GetFileNameWithoutExtension(originalFileName);
                    string fileExt = Path.GetExtension(originalFileName);

                    if (string.IsNullOrWhiteSpace(fileExt) || Array.IndexOf(AllowedDocumentExtensions, fileExt.ToLowerInvariant()) < 0)
                    {
                        continue;
                    }

                    if (!Directory.Exists(basePath))
                    {
                        Directory.CreateDirectory(basePath);
                    }

                    string filePath = Path.Combine(basePath, originalFileName);

                    fileUpload.SaveAs(filePath);

                    FileAttachment file = new FileAttachment
                    {
                        FileName = fileNameWithoutExt,
                        FilePath = filePath,
                        DocumentMasterId = documentMasterId,
                        ReferenceNumber = string.Empty,
                        EmailId = employeeEmail
                    };

                    userDocBL.SaveUserDocument(userId, file, fileExt, basePath);
                }
                catch (Exception ex)
                {
                    CommonBL errorlog = new CommonBL();
                    errorlog.fnStoreErrorLog("EmployeeRegistration", "SaveEmployeeDocuments", "Exception Message: " + ex.Message + " StackTrace: " + ex.StackTrace, UserId);
                }
            }
        }

        private EmployeeOnboardingDO BuildEmployeeOnboarding()
        {
            string fullName = string.Join(" ", new[]
            {
                ValueOf(txtFirstName),
                ValueOf(txtMiddleName),
                ValueOf(txtLastName)
            }).Replace("  ", " ").Trim();

            return new EmployeeOnboardingDO
            {
                UserId = ParseInt(Request.QueryString["user_id"]),
                EmployeeCode = ValueOf(txtEmployeeCode),
                Username = ValueOf(txtUsername),
                FullName = fullName,
                Email = ValueOf(txtEmail),
                Contact = ValueOf(txtMobileNumber),
                Gender = SelectedValueOf(ddlGender),
                DateOfBirth = ParseDate(ValueOf(txtDateOfBirth)),
                MaritalStatus = SelectedValueOf(ddlMaritalStatus),
                BloodGroup = SelectedValueOf(ddlBloodGroup),
                Nationality = SelectedValueOf(ddlNationality),
                EmploymentType = SelectedValueOf(ddlEmploymentType),
                EmployeeCategory = SelectedValueOf(ddlEmployeeCategory),
              
                JoiningDate = ParseDate(ValueOf(txtJoiningDate)),
                //ConfirmationDate = ParseDate(ValueOf(txtConfirmationDate)),
                //ProbationEndDate = ParseDate(ValueOf(txtProbationEndDate)),
                RetirementDate = null,
                ProbationMonths = ParseInt(SelectedValueOf(ddlProbationPeriod)),
                EmployeeStatus = SelectedValueOf(ddlEmployeeStatus),
                EmployeeSubStatus = SelectedValueOf(ddlEmployeeSubStatus),
                NoticePeriod = ParseInt(ValueOf(txtNoticePeriod)),
                ExitDate = ParseDate(ValueOf(txtExitDate)),
                SeparationReason = SelectedValueOf(ddlSeparationReason),
                //Company = SelectedValueOf(ddlCompany),
                Department = SelectedValueOf(ddlDepartment),
                BranchOffice = ValueOf(txtBranchOffice),
                Location = ValueOf(txtLocation),
                ReportingManagerId = ParseInt(ddlReportingManager.SelectedValue),
                //FunctionalManagerId = ParseInt(ddlFunctionalManager.SelectedValue),
                HodId = ParseInt(ddlHod.SelectedValue),
                Designation = SelectedValueOf(ddlDesignation),
                //EmployeeLevel = SelectedValueOf(ddlEmployeeLevel),
                AttendanceType = SelectedValueOf(ddlAttendanceType),
                WeeklyOff = SelectedValueOf(ddlWeeklyOff),
                WorkingHours = NormalizeWorkingHours(ValueOf(txtWorkingHours)),
                AttendancePolicy = SelectedValueOf(ddlAttendancePolicy),
                PunchingDeviceId = ValueOf(txtPunchingDeviceId),
                BiometricId = ValueOf(txtBiometricId),
                OvertimeEligible = chkOvertimeEligible.Checked ? "60" : "61",
                OvertimeRate = chkOvertimeEligible.Checked ? ParseDecimal(ValueOf(txtOvertimeRate)) : 0,
                WorkLocation = SelectedValueOf(ddlWorkLocation),
                RemoteWorkAllowed = "0",
                // Payroll is handled outside Employee Registration, so no payroll values are submitted here.
                // SalaryStructure = string.Empty,
                // BasicSalary = 0,
                // GrossSalary = 0,
                // Ctc = 0,
                // SalaryEffectiveDate = null,
                // PaymentMode = string.Empty,
                // UanNumber = string.Empty,
                // PfNumber = string.Empty,
                // EsicNumber = string.Empty,
                // ProfessionalTaxNumber = string.Empty,
                // LabourWelfareFundNumber = string.Empty,
                // TaxRegime = string.Empty,
                // TdsApplicable = string.Empty,
                InsertedBy = ParseInt(Convert.ToString(Session["userId"]))
            };
        }

        private int GetProbationMonths()
        {
            DateTime? joiningDate = ParseDate(ValueOf(txtJoiningDate));
            // DateTime? probationEndDate = ParseDate(ValueOf(txtProbationEndDate));
            //if (!joiningDate.HasValue || !probationEndDate.HasValue || probationEndDate.Value <= joiningDate.Value)
            //{
            //    return 0;
            //}

            //return ((probationEndDate.Value.Year - joiningDate.Value.Year) * 12) + probationEndDate.Value.Month - joiningDate.Value.Month;
            return 0;
        }

        private string TextOf(DropDownList ddl)
        {
            return ddl.SelectedIndex > 0 ? ddl.SelectedItem.Text.Trim() : string.Empty;
        }

        private string NormalizeWorkingHours(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return string.Empty;
            }

            TimeSpan parsed;
            if (TimeSpan.TryParse(value.Trim(), out parsed))
            {
                return parsed.ToString(@"hh\:mm\:ss");
            }

            return value.Trim();
        }

        private string SelectedValueOf(DropDownList ddl)
        {
            if (ddl == null)
            {
                return string.Empty;
            }

            if (ddl.SelectedIndex > 0)
            {
                return Convert.ToString(ddl.SelectedValue ?? string.Empty).Trim();
            }

            string postedValue = Request.Form[ddl.UniqueID];
            return Convert.ToString(postedValue ?? string.Empty).Trim();
        }

        private string ValueOf(HtmlInputControl input)
        {
            return input == null ? string.Empty : Convert.ToString(input.Value ?? string.Empty).Trim();
        }

        private bool IsYesValue(string value, string text)
        {
            string normalizedValue = Convert.ToString(value ?? string.Empty).Trim();
            string normalizedText = Convert.ToString(text ?? string.Empty).Trim();

            return normalizedValue == "1"
                || normalizedValue.Equals("yes", StringComparison.OrdinalIgnoreCase)
                || normalizedValue.Equals("true", StringComparison.OrdinalIgnoreCase)
                || normalizedText.Equals("yes", StringComparison.OrdinalIgnoreCase)
                || normalizedText.Equals("true", StringComparison.OrdinalIgnoreCase);
        }

        private DateTime? ParseDate(string value)
        {
            DateTime parsed;
            if (DateTime.TryParse(value, out parsed))
            {
                return parsed;
            }
            return null;
        }

        private int ParseInt(string value)
        {
            int parsed;
            return int.TryParse(Convert.ToString(value), out parsed) ? parsed : 0;
        }

        private decimal ParseDecimal(string value)
        {
            decimal parsed;
            return decimal.TryParse(Convert.ToString(value), out parsed) ? parsed : 0;
        }
    }
}
