//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.View.Modules
{


    public partial class SalarySlip
    {

        /// <summary>
        /// ddlYear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;

        /// <summary>
        /// ddlFromMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFromMonth;

        /// <summary>
        /// ddlToMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlToMonth;

        /// <summary>
        /// ddlEmployee control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEmployee;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// pnlResults control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlResults;

        /// <summary>
        /// gvSlips control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvSlips;

        /// <summary>
        /// pnlNoData control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoData;
    }
}
