CREATE DEFINER=`scadmin`@`%` PROCEDURE `SP_SaveEmployeeOnboarding`(
    IN p_user_id INT,
    IN p_emp_code VARCHAR(50),
    IN p_username VARCHAR(100),
    IN p_fullname VARCHAR(150),
    IN p_email VARCHAR(150),
    IN p_contact VARCHAR(20),
   
    IN p_gender INT,
    IN p_dob DATE,
    IN p_marital_status INT,
    IN p_blood_group INT,
    IN p_nationality INT,

    IN p_employment_type INT,
    IN p_employee_category INT,
    IN p_joining_date DATE,
    IN p_confirmation_date DATE,
    IN p_probation_end_date DATE,
    IN p_retirement_date DATE,
    IN p_probation_months INT,
    IN p_employee_status INT,
	IN p_employee_sub_status INT, -- sagar 13/07/2026
    IN p_notice_period INT,
    IN p_exit_date DATE,
    IN p_separation_reason INT,

    IN p_company INT,
    IN p_department INT,
    IN p_branch_office VARCHAR(100),
    IN p_location VARCHAR(100),
    IN p_reporting_manager_id INT,
    IN p_functional_manager_id INT,
    IN p_hod_id INT,
    IN p_designation INT,
    IN p_employee_level INT,

    IN p_attendance_type INT,
    IN p_weekly_off INT,
    IN p_working_hours TIME,
    IN p_attendance_policy INT,
    IN p_punching_device_id VARCHAR(100),
    IN p_biometric_id VARCHAR(100),
    IN p_overtime_eligible INT,
    IN p_overtime_rate DECIMAL(18,2),
    IN p_work_location INT,
    IN p_remote_work_allowed INT,

    IN p_inserted_by INT,
    IN p_PF_no varchar(200)
)
BEGIN
    DECLARE v_user_id INT DEFAULT 0;
    DECLARE v_step VARCHAR(100) DEFAULT 'Start';
    DECLARE v_password VARCHAR(100) DEFAULT 'Pass@123';
    DECLARE v_encrypt VARBINARY(255);

DECLARE v_total_leaves INT DEFAULT 0;
DECLARE v_privilege_leaves INT DEFAULT 0;
DECLARE v_casual_leaves INT DEFAULT 0;
DECLARE v_sick_leaves INT DEFAULT 0;
 DECLARE p_prev_emp_code VARCHAR(50) ;
 DECLARE v_new_emp_code VARCHAR(20);


    DECLARE v_err_code INT DEFAULT 0;
    DECLARE v_err_msg TEXT DEFAULT '';

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        GET DIAGNOSTICS CONDITION 1
            v_err_code = MYSQL_ERRNO,
            v_err_msg = MESSAGE_TEXT;
        ROLLBACK;
        SELECT
            'Failed' AS Status,
            CONCAT('Employee onboarding save failed at: ', v_step, ' - [', v_err_code, '] ', v_err_msg) AS Message,
            0 AS UserId,
            '' AS Username,
            '' AS AutoGeneratedPassword;
    END;

    SET p_emp_code = NULLIF(TRIM(p_emp_code), '');
    SET p_username = NULLIF(TRIM(p_username), '');
    SET p_fullname = NULLIF(TRIM(p_fullname), '');
    SET p_email = NULLIF(TRIM(p_email), '');
    SET p_contact = NULLIF(TRIM(p_contact), '');
    SET p_branch_office = NULLIF(TRIM(p_branch_office), '');
    SET p_location = NULLIF(TRIM(p_location), '');
    SET p_punching_device_id = NULLIF(TRIM(p_punching_device_id), '');
    SET p_biometric_id = NULLIF(TRIM(p_biometric_id), '');

    -- If the supplied employee code is already taken, auto-generate the next
    -- sequential one instead of blocking the save (e.g. ALPH003 -> ALPH004).
    IF EXISTS (
        SELECT 1
        FROM lean_mngt.userm
        WHERE emp_code = p_emp_code
        LIMIT 1
    ) THEN
        CALL lean_mngt.get_next_emp_code(v_new_emp_code);
        SET p_emp_code = v_new_emp_code;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM lean_mngt.userm
        WHERE username = p_username
        
        LIMIT 1
    ) THEN
        SELECT 'Failed' AS Status, 'Username already exists.' AS Message, 0 AS UserId, '' AS Username, '' AS AutoGeneratedPassword;

    ELSEIF EXISTS (
        SELECT 1
        FROM lean_mngt.userm
        WHERE user_mail_id = p_email
      
        LIMIT 1
    ) THEN
        SELECT 'Failed' AS Status, 'Email ID already exists.' AS Message, 0 AS UserId, '' AS Username, '' AS AutoGeneratedPassword;

    ELSEIF EXISTS (
        SELECT 1
        FROM lean_mngt.userm
        WHERE contact_detail = p_contact
        
        LIMIT 1
    ) THEN
        SELECT 'Failed' AS Status, 'Mobile Number already exists.' AS Message, 0 AS UserId, '' AS Username, '' AS AutoGeneratedPassword;

    ELSE
        START TRANSACTION;

        SET v_step = 'Insert userm';


IF EXISTS (
    SELECT 1
    FROM lean_mngt.userm
    WHERE PF_no = p_PF_no
      AND IFNULL(p_PF_no,'') <> ''
) THEN

    UPDATE lean_mngt.userm
    SET PF_no = p_PF_no,
        updated_by = p_inserted_by,
        updated_date = NOW()
    WHERE PF_no = p_PF_no;

ELSE
        INSERT INTO lean_mngt.userm
        (
            emp_code,
            username,
            user_fullname,
            user_mail_id,
            contact_detail,
            display_name,
            user_type,
            is_active,
            user_statusflag,
            pass_resetflag,
            wrong_pass_count,
            allowmultipleRoles,
            LoginStatusFlag,
            gender,
            DOB,
            marital_status,
            blood_group,
            nationality,
            employment_type,
            employee_type,
            date_of_joining,
            probation_period_months,
            employee_status,
            employee_sub_status,
            notice_period,
            exit_date,
            separation_reason,
            retirement_date,
            inserted_by,
            inserted_date,
            reporting_manager,
            company_id,
            PF_no
        )
        VALUES
        (
            p_emp_code,
            p_username,
            p_fullname,
            p_email,
            p_contact,
            p_username,
            2,
            1,
            1,
            0,
            0,
            0,
            0,
            NULLIF(p_gender, 0),
            p_dob,
            NULLIF(p_marital_status, 0),
            NULLIF(p_blood_group, 0),
            NULLIF(p_nationality, 0),
            NULLIF(p_employment_type, 0),
            NULLIF(p_employee_category, 0),
            p_joining_date,
            IFNULL(p_probation_months, 0),
            NULLIF(p_employee_status, 0),
             NULLIF(p_employee_sub_status, 0),
            IFNULL(p_notice_period, 0),
            p_exit_date,
            NULLIF(p_separation_reason, 0),
            p_retirement_date,
            IFNULL(p_inserted_by, 0),
            NOW(),
            NULLIF(p_reporting_manager_id, 0),
            3,
            p_PF_no
        );

END IF;
        SET v_user_id = LAST_INSERT_ID();

        SET v_step = 'Insert employee_official_contact_history';

        INSERT INTO lean_mngt.employee_official_contact_history
        (
            user_id,
            official_email,
            official_mobile,
            is_active,
            inserted_by,
            inserted_date
        )
        VALUES
        (
            v_user_id,
            p_email,
            p_contact,
            1,
            IFNULL(p_inserted_by, 0),
            NOW()
        );

        SET v_step = 'Insert password';

        SET v_encrypt = AES_ENCRYPT(v_password, '@lphon$0l#123');

        INSERT INTO lean_mngt.passM
        (
            password,
            user_id,
            inserted_by,
            inserted_date
        )
        VALUES
        (
            v_encrypt,
            v_user_id,
            IFNULL(p_inserted_by, 0),
            NOW()
        );

        INSERT INTO lean_mngt.passwordtrans
        (
            user_id,
            password,
            insertedby,
            inserteddate
        )
        VALUES
        (
            v_user_id,
            v_encrypt,
            IFNULL(p_inserted_by, 0),
            NOW()
        );

        SET v_step = 'Insert userroledetails';

        INSERT INTO lean_mngt.userroledetails
        (
            userloginid,
            roleid,
            isactive,
            inserteddate,
            insertedby
        )
        VALUES
        (
            v_user_id,
            2,
            1,
            NOW(),
            IFNULL(p_inserted_by, 0)
        );

        SET v_step = 'Insert employee_organization';

        INSERT INTO lean_mngt.employee_organization
        (
            employee_id,
            company,
            department,
            branch_office,
            location,
            reporting_manager_id,
            functional_manager_id,
            hod_id,
            designation,
            employee_level,
            created_date,
            isactive
        )
        VALUES
        (
            v_user_id,
            -- NULLIF(p_company, 0),
            3,
            NULLIF(p_department, 0),
            p_branch_office,
            p_location,
            NULLIF(p_reporting_manager_id, 0),
            NULLIF(p_functional_manager_id, 0),
            NULLIF(p_hod_id, 0),
            NULLIF(p_designation, 0),
            NULLIF(p_employee_level, 0),
            NOW(),
            1
        );

        SET v_step = 'Insert emp_probation_management';

       INSERT INTO lean_mngt.emp_probation_management
(
    user_id,
    joining_date,
    probation_month,
    extended_probation_days,
    extended_probation_month,
    probation_status,
    probation_end_date,
    probation_remarks,
    inserted_by,
    inserted_date,
    is_active,
    confirmation_date
)
VALUES
(
    v_user_id,
    p_joining_date,
    IFNULL(p_probation_months, 0),
    0,
    0,
    CASE WHEN IFNULL(p_probation_months, 0) = 0 THEN 'No Probation Applicable' ELSE 'Pending' END,
    COALESCE(
        p_probation_end_date,
        DATE_ADD(p_joining_date, INTERVAL IFNULL(p_probation_months, 0) MONTH)
    ),
    'Probation initiated at employee creation',
    IFNULL(p_inserted_by, 0),
    NOW(),
    1,
    p_confirmation_date
);

        SET v_step = 'Insert employee_attendance_settings';

        INSERT INTO lean_mngt.employee_attendance_settings
        (
            user_id,
            attendance_type,
            weekly_off,
            working_hours,
            punching_device_id,
            biometric_id,
            attendance_policy,
            overtime_eligible,
            overtime_rate,
            work_location,
            remote_work_allowed,
            is_active,
            inserted_by,
            inserted_date,
            updated_by,
            updated_date
        )
        VALUES
        (
            v_user_id,
            NULLIF(p_attendance_type, 0),
            NULLIF(p_weekly_off, 0),
            p_working_hours,
            p_punching_device_id,
            p_biometric_id,
            NULLIF(p_attendance_policy, 0),
            IFNULL(p_overtime_eligible, 0),
            IFNULL(p_overtime_rate, 0),
            NULLIF(p_work_location, 0),
            IFNULL(p_remote_work_allowed, 0),
            1,
            IFNULL(p_inserted_by, 0),
            NOW(),
            IFNULL(p_inserted_by, 0),
            NOW()
        );
        
      SET v_step = 'Insert Employee Leave Allocation';

IF IFNULL(p_probation_months, 0) > 0 THEN

    INSERT INTO lean_mngt.Employee_wise_total_leaves
    (
        user_id,
        company_id,
        total_leaves,
        privilage,
        casual,
        sick,
        is_probation,
        inserted_date,
        inserted_by,
        is_active
    )
    VALUES
    (
        v_user_id,
        3,
      --  NULLIF(p_company, 0),
        0,
        0,
        0,
        0,
        1,
        NOW(),
        p_inserted_by,
        1
    );

ELSE

    SELECT
        total_leaves,
        privilege_leaves,
        casual_leaves,
        sick_leaves
    INTO
        v_total_leaves,
        v_privilege_leaves,
        v_casual_leaves,
        v_sick_leaves
    FROM lean_mngt.CompanyLeaveMaster
    WHERE company_id = 3   -- default 3 for now
      AND is_active = 1
    LIMIT 1;

   INSERT INTO lean_mngt.Employee_wise_total_leaves
     (
        user_id,
        company_id,
        total_leaves,
        privilage,
        casual,
        sick,
        is_probation,
        inserted_date,
        inserted_by,
        is_active
    )
    VALUES
    (
        v_user_id,
        3,
       -- NULLIF(p_company, 0),
        IFNULL(v_total_leaves, 0),
        IFNULL(v_privilege_leaves, 0),
        IFNULL(v_casual_leaves, 0),
        IFNULL(v_sick_leaves, 0),
        0,
        NOW(),
        p_inserted_by,
        1
    );

END IF;

        COMMIT;

        SELECT
            'Success' AS Status,
            'Employee Created Successfully' AS Message,
            v_user_id AS UserId,
            p_username AS Username,
            v_password AS AutoGeneratedPassword;
    END IF;
END